### ISSUE TITLE
 undefined method `create_pool' for an instance of Fog::Libvirt::Compute::Real (NoMethodError)

### ISSUE THREAD

**Issue by davispuh** [fog/fog-libvirt#147]
When doing
```ruby
compute = Fog::Compute.new(provider: :libvirt, libvirt_uri: 'qemu:///session')
compute.pools.create(xml: xml)
```

It fails with
```
fog-libvirt-0.12.0/lib/fog/libvirt/models/compute/pool.rb:28:in `save': undefined method `create_pool' for an instance of Fog::Libvirt::Compute::Real (NoMethodError)

          self.uuid = (persistent ? service.define_pool(xml) : service.create_pool(xml)).uuid
                                                                      ^^^^^^^^^^^^
Did you mean?  create_volume
        from fog-core-2.4.0/lib/fog/core/collection.rb:53:in `create'
```

There is no such method `create_pool`. See [models/compute/pool.rb#L28](/fog/fog-libvirt/blob/master/lib/fog/libvirt/models/compute/pool.rb#L28)

**Comment by ekohl** [comment]
Did this ever work or is this a regression? In 476c6305ebaa25dc12bea275f8583aaf6312aa90 I did implement a new `to_xml` method since in 09b68517d99dc64e3de2b9cb42477d76c5e7a458 I removed the XML template but I don't see how it would cause this. The specific line was part of 192adc0808d1d30c867f9fdb1a35a57193cc22b9 but I can't find definition of `create_pool` in the source code.

How about creating a persistent pool?
```ruby
compute = Fog::Compute.new(provider: :libvirt, libvirt_uri: 'qemu:///session')
compute.pools.create(xml: xml, persistent: true)
```

**Comment by davispuh** [comment]
Don't know if it ever worked before as this was first time trying to use it. It's possible it never worked.

With `persistent: true` it works fine without any issues.
